### ISSUE TITLE
Ubuntu support

### ISSUE THREAD

**Issue by rezacsedu** [SkymindIO/SKIL-CE#32] opened 2018-03-29 20:55 UTC
Hi there,

I would like to install SKIL on Ubuntu. Is there any plan for the Ubuntu users?

**Comment by tomthetrainer** [comment] 2018-03-30 14:29
@nkwoh01 
Do you have a roadmap for ubuntu support?

**Comment by tomthetrainer** [comment] 2018-03-30 14:33
You could use the docker image with Skil CE pre-installed. 
https://docs.skymind.ai/docs/docker-image

**Comment by ShamsUlAzeem** [comment] 2019-02-21 22:22
Duplicate of #8

**Closed** 2019-04-24 19:06 UTC
